// Dados mockados que simulam a extração do Jira (seção 2 do spec).
// Estrutura pronta para ser substituída por um adaptador real de API
// (ver src/jiraAdapter.ts) sem alterar nenhuma tela.

import type {
  Ceremony,
  Epic,
  Parecer,
  ReleaseCutoff,
  SecurityAssessment,
  Story,
  Task,
  ThirdPartyInfo,
} from './types'

const noSecurity: SecurityAssessment = {
  status: 'N/A',
  date: null,
  owner: null,
  deadline: null,
  notes: '',
}

const noThirdParty: ThirdPartyInfo | null = null

let taskSeq = 1
let storySeq = 1

function task(title: string, assignee: string, size: number, dueDate: string, status: Task['status'], updatedAt: string): Task {
  const n = taskSeq++
  return { id: `t${n}`, key: `TASK-${200 + n}`, title, assignee, size, dueDate, status, updatedAt }
}

function story(partial: Omit<Story, 'id' | 'key'>): Story {
  const n = storySeq++
  return { id: `s${n}`, key: `HIST-${300 + n}`, ...partial }
}

export const epics: Epic[] = [
  {
    id: 'e1',
    key: 'EPIC-101',
    title: 'Abertura de Conta PJ Digital',
    technologies: ['Frontend', 'Backend'],
    squads: ['Squad Onboarding', 'Squad Core Bancário'],
    milestoneDate: '2026-09-15',
    dueDate: '2026-10-30',
    stories: [
      story({
        title: 'Formulário de cadastro PJ com validação de CNPJ',
        status: 'Em Andamento',
        technology: 'Frontend',
        squad: 'Squad Onboarding',
        size: 8,
        startDate: '2026-08-04',
        dueDate: '2026-08-29',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Nenhuma', status: 'concluído', expectedDate: null },
        thirdParty: noThirdParty,
        security: { status: 'pendente', date: null, owner: 'Time Segurança', deadline: '2026-08-27', notes: 'Revisão de mascaramento de dados sensíveis' },
        risk: { level: 'médio', reason: 'Parecer de segurança ainda pendente perto do prazo' },
        releaseCutoffId: 'rc-web-1',
        updatedAt: '2026-08-20',
        tasks: [
          task('Layout responsivo do formulário', 'Ana Lima', 3, '2026-08-22', 'Concluído', '2026-08-19'),
          task('Integração validação Receita Federal', 'Bruno Melo', 5, '2026-08-28', 'Em Andamento', '2026-08-20'),
        ],
      }),
      story({
        title: 'Serviço de análise de risco de crédito PJ',
        status: 'Bloqueado',
        technology: 'Backend',
        squad: 'Squad Core Bancário',
        size: 13,
        startDate: '2026-08-04',
        dueDate: '2026-09-05',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'HX', status: 'bloqueado', expectedDate: '2026-09-01' },
        thirdParty: noThirdParty,
        security: noSecurity,
        risk: { level: 'alto', reason: 'Bloqueado aguardando API de score da HX' },
        releaseCutoffId: null,
        updatedAt: '2026-08-18',
        tasks: [
          task('Modelagem do motor de score', 'Carla Nogueira', 8, '2026-08-30', 'Em Andamento', '2026-08-18'),
          task('Contrato de integração com HX', 'Diego Santos', 5, '2026-09-02', 'Bloqueado', '2026-08-15'),
        ],
      }),
    ],
  },
  {
    id: 'e2',
    key: 'EPIC-102',
    title: 'Pix por Aproximação (NFC)',
    technologies: ['iOS', 'Android', 'Backend'],
    squads: ['Squad Mobile iOS', 'Squad Mobile Android', 'Squad Core Bancário'],
    milestoneDate: '2026-09-10',
    dueDate: '2026-09-25',
    stories: [
      story({
        title: 'Leitura de NFC para pagamento por aproximação',
        status: 'Em Andamento',
        technology: 'iOS',
        squad: 'Squad Mobile iOS',
        size: 8,
        startDate: '2026-08-10',
        dueDate: '2026-09-08',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Nenhuma', status: 'concluído', expectedDate: null },
        thirdParty: noThirdParty,
        security: { status: 'aprovado', date: '2026-08-12', owner: 'Time Segurança', deadline: '2026-08-12', notes: 'Aprovado com monitoramento de fraude ativo' },
        risk: { level: 'baixo', reason: 'Sem pendências' },
        releaseCutoffId: 'rc-ios-1',
        updatedAt: '2026-08-19',
        tasks: [
          task('Implementar leitor NFC nativo', 'Felipe Rocha', 5, '2026-09-01', 'Em Andamento', '2026-08-19'),
        ],
      }),
      story({
        title: 'Leitura de NFC para pagamento por aproximação (Android)',
        status: 'Em Andamento',
        technology: 'Android',
        squad: 'Squad Mobile Android',
        size: 8,
        startDate: '2026-08-10',
        dueDate: '2026-09-08',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Nenhuma', status: 'concluído', expectedDate: null },
        thirdParty: noThirdParty,
        security: { status: 'aprovado', date: '2026-08-12', owner: 'Time Segurança', deadline: '2026-08-12', notes: 'Aprovado com monitoramento de fraude ativo' },
        risk: { level: 'baixo', reason: 'Sem pendências' },
        releaseCutoffId: 'rc-android-1',
        updatedAt: '2026-08-19',
        tasks: [
          task('Implementar HCE (Host Card Emulation)', 'Giovana Alves', 5, '2026-09-01', 'Em Andamento', '2026-08-19'),
        ],
      }),
      story({
        title: 'Endpoint de autorização de transação por aproximação',
        status: 'A Fazer',
        technology: 'Backend',
        squad: 'Squad Core Bancário',
        size: 5,
        startDate: '2026-08-25',
        dueDate: '2026-09-12',
        completedDate: null,
        sprint: 'Sprint 35',
        externalDependency: { type: 'Nenhuma', status: 'não iniciado', expectedDate: null },
        thirdParty: noThirdParty,
        security: { status: 'pendente', date: null, owner: 'Time Segurança', deadline: '2026-09-05', notes: 'Aguardando avaliação de limites antifraude' },
        risk: { level: 'médio', reason: 'Depende de parecer de segurança antes do corte' },
        releaseCutoffId: null,
        updatedAt: '2026-08-14',
        tasks: [
          task('Definir regras de limite por transação', 'Diego Santos', 3, '2026-09-08', 'A Fazer', '2026-08-14'),
        ],
      }),
    ],
  },
  {
    id: 'e3',
    key: 'EPIC-103',
    title: 'Redesenho do Extrato no Web Banking',
    technologies: ['Web Banking', 'Backend'],
    squads: ['Squad Web Banking', 'Squad Core Bancário'],
    milestoneDate: '2026-09-20',
    dueDate: '2026-10-10',
    stories: [
      story({
        title: 'Novo layout de extrato com filtros avançados',
        status: 'Em Andamento',
        technology: 'Web Banking',
        squad: 'Squad Web Banking',
        size: 8,
        startDate: '2026-08-11',
        dueDate: '2026-09-04',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Nenhuma', status: 'não iniciado', expectedDate: null },
        thirdParty: noThirdParty,
        security: noSecurity,
        risk: { level: 'baixo', reason: 'Sem pendências' },
        releaseCutoffId: 'rc-web-1',
        updatedAt: '2026-08-20',
        tasks: [
          task('Componente de filtros por período e categoria', 'Helena Prado', 5, '2026-08-29', 'Em Andamento', '2026-08-20'),
          task('Exportação de extrato em PDF/CSV', 'Igor Teixeira', 3, '2026-09-02', 'A Fazer', '2026-08-11'),
        ],
      }),
      story({
        title: 'Categorização automática de transações',
        status: 'A Fazer',
        technology: 'Backend',
        squad: 'Squad Core Bancário',
        size: 13,
        startDate: '2026-09-01',
        dueDate: '2026-09-30',
        completedDate: null,
        sprint: 'Sprint 35',
        externalDependency: { type: 'Nenhuma', status: 'não iniciado', expectedDate: null },
        thirdParty: noThirdParty,
        security: noSecurity,
        risk: { level: 'baixo', reason: 'Sem pendências' },
        releaseCutoffId: null,
        updatedAt: '2026-08-10',
        tasks: [
          task('Treinar modelo de categorização', 'Carla Nogueira', 8, '2026-09-20', 'A Fazer', '2026-08-10'),
        ],
      }),
    ],
  },
  {
    id: 'e4',
    key: 'EPIC-104',
    title: 'Atendimento Digital via HX',
    technologies: ['Frontend', 'Backend'],
    squads: ['Squad Onboarding', 'Squad Integrações'],
    milestoneDate: '2026-09-18',
    dueDate: '2026-10-15',
    stories: [
      story({
        title: 'Widget de chat de atendimento embarcado no app',
        status: 'Bloqueado',
        technology: 'Frontend',
        squad: 'Squad Onboarding',
        size: 8,
        startDate: '2026-08-01',
        dueDate: '2026-08-26',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'HX', status: 'bloqueado', expectedDate: '2026-09-05' },
        thirdParty: noThirdParty,
        security: noSecurity,
        risk: { level: 'alto', reason: 'Ambiente de homologação da HX indisponível há 12 dias' },
        releaseCutoffId: null,
        updatedAt: '2026-08-17',
        tasks: [
          task('Integrar SDK de chat da HX', 'Ana Lima', 5, '2026-08-25', 'Bloqueado', '2026-08-17'),
        ],
      }),
      story({
        title: 'Sincronização de histórico de atendimento',
        status: 'A Fazer',
        technology: 'Backend',
        squad: 'Squad Integrações',
        size: 5,
        startDate: '2026-08-25',
        dueDate: '2026-09-15',
        completedDate: null,
        sprint: 'Sprint 35',
        externalDependency: { type: 'HX', status: 'em andamento', expectedDate: '2026-09-05' },
        thirdParty: noThirdParty,
        security: noSecurity,
        risk: { level: 'médio', reason: 'Depende da API de histórico da HX ainda em desenvolvimento' },
        releaseCutoffId: null,
        updatedAt: '2026-08-12',
        tasks: [
          task('Consumir API de histórico da HX', 'Diego Santos', 5, '2026-09-12', 'A Fazer', '2026-08-12'),
        ],
      }),
    ],
  },
  {
    id: 'e5',
    key: 'EPIC-105',
    title: 'Cadastro de Parceiros Comerciais via Sales Force',
    technologies: ['Backend'],
    squads: ['Squad Integrações'],
    milestoneDate: '2026-09-22',
    dueDate: '2026-10-20',
    stories: [
      story({
        title: 'Sincronização bidirecional de cadastro de parceiros',
        status: 'Em Andamento',
        technology: 'Backend',
        squad: 'Squad Integrações',
        size: 13,
        startDate: '2026-08-05',
        dueDate: '2026-09-10',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Sales Force', status: 'em andamento', expectedDate: '2026-09-08' },
        thirdParty: { company: 'Salesforce Brasil Ltda.', homologationStatus: 'em andamento', requestedDate: '2026-07-20', expectedDate: '2026-09-05', completedDate: null },
        security: { status: 'pendente', date: null, owner: 'Time Segurança', deadline: '2026-09-01', notes: 'Avaliação de fluxo de dados com terceiro' },
        risk: { level: 'médio', reason: 'Homologação do terceiro e parecer de segurança em paralelo, ambos correndo perto do prazo' },
        releaseCutoffId: null,
        updatedAt: '2026-08-20',
        tasks: [
          task('Mapear campos do objeto Partner no Salesforce', 'Bruno Melo', 5, '2026-08-28', 'Concluído', '2026-08-18'),
          task('Implementar webhook de atualização', 'Carla Nogueira', 8, '2026-09-05', 'Em Andamento', '2026-08-20'),
        ],
      }),
    ],
  },
  {
    id: 'e6',
    key: 'EPIC-106',
    title: 'Simulador de Crédito no Portal Institucional',
    technologies: ['Frontend'],
    squads: ['Squad Onboarding'],
    milestoneDate: '2026-09-05',
    dueDate: '2026-09-19',
    stories: [
      story({
        title: 'Publicação do simulador no site institucional',
        status: 'Em Homologação',
        technology: 'Frontend',
        squad: 'Squad Onboarding',
        size: 5,
        startDate: '2026-07-28',
        dueDate: '2026-08-25',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Sites', status: 'em andamento', expectedDate: '2026-08-24' },
        thirdParty: noThirdParty,
        security: { status: 'aprovado', date: '2026-08-10', owner: 'Time Segurança', deadline: '2026-08-10', notes: 'Sem pendências' },
        risk: { level: 'baixo', reason: 'Aguardando apenas publicação pelo time de Sites' },
        releaseCutoffId: null,
        updatedAt: '2026-08-19',
        tasks: [
          task('Ajustes de SEO e performance', 'Ana Lima', 3, '2026-08-22', 'Concluído', '2026-08-19'),
          task('Publicação em produção pelo time de Sites', 'Time Sites', 2, '2026-08-24', 'Em Andamento', '2026-08-19'),
        ],
      }),
    ],
  },
  {
    id: 'e7',
    key: 'EPIC-107',
    title: 'Biometria Facial no App iOS',
    technologies: ['iOS'],
    squads: ['Squad Mobile iOS'],
    milestoneDate: '2026-09-12',
    dueDate: '2026-09-26',
    stories: [
      story({
        title: 'Cadastro e validação de biometria facial (Face ID)',
        status: 'Em Andamento',
        technology: 'iOS',
        squad: 'Squad Mobile iOS',
        size: 13,
        startDate: '2026-08-01',
        dueDate: '2026-08-30',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Nenhuma', status: 'concluído', expectedDate: null },
        thirdParty: noThirdParty,
        security: { status: 'reprovado', date: '2026-08-15', owner: 'Time Segurança', deadline: '2026-08-15', notes: 'Necessário reforçar armazenamento local do template biométrico' },
        risk: { level: 'alto', reason: 'Parecer de segurança reprovado — requer retrabalho antes de nova avaliação' },
        releaseCutoffId: 'rc-ios-1',
        updatedAt: '2026-08-16',
        tasks: [
          task('Ajustar armazenamento seguro (Secure Enclave)', 'Felipe Rocha', 8, '2026-08-28', 'Em Andamento', '2026-08-16'),
        ],
      }),
    ],
  },
  {
    id: 'e8',
    key: 'EPIC-108',
    title: 'Widget de Saldo na Tela Inicial (Android)',
    technologies: ['Android'],
    squads: ['Squad Mobile Android'],
    milestoneDate: '2026-08-29',
    dueDate: '2026-09-08',
    stories: [
      story({
        title: 'Widget de home screen com saldo e últimas transações',
        status: 'Concluído',
        technology: 'Android',
        squad: 'Squad Mobile Android',
        size: 5,
        startDate: '2026-07-25',
        dueDate: '2026-08-15',
        completedDate: '2026-08-14',
        sprint: 'Sprint 33',
        externalDependency: { type: 'Nenhuma', status: 'concluído', expectedDate: null },
        thirdParty: noThirdParty,
        security: { status: 'aprovado', date: '2026-08-10', owner: 'Time Segurança', deadline: '2026-08-10', notes: 'Sem pendências' },
        risk: { level: 'baixo', reason: 'Concluído' },
        releaseCutoffId: 'rc-android-1',
        updatedAt: '2026-08-14',
        tasks: [
          task('Implementar widget nativo', 'Giovana Alves', 5, '2026-08-14', 'Concluído', '2026-08-14'),
        ],
      }),
    ],
  },
  {
    id: 'e9',
    key: 'EPIC-109',
    title: 'Autenticação Forte (MFA) no Web Banking',
    technologies: ['Web Banking', 'Backend'],
    squads: ['Squad Web Banking', 'Squad Core Bancário'],
    milestoneDate: '2026-09-08',
    dueDate: '2026-09-24',
    stories: [
      story({
        title: 'Segundo fator via aplicativo autenticador',
        status: 'Em Andamento',
        technology: 'Web Banking',
        squad: 'Squad Web Banking',
        size: 8,
        startDate: '2026-08-08',
        dueDate: '2026-09-01',
        completedDate: null,
        sprint: 'Sprint 34',
        externalDependency: { type: 'Nenhuma', status: 'não iniciado', expectedDate: null },
        thirdParty: noThirdParty,
        security: { status: 'pendente', date: null, owner: 'Time Segurança', deadline: '2026-08-26', notes: 'Avaliação do fluxo de fallback de MFA' },
        risk: { level: 'médio', reason: 'Parecer de segurança pendente próximo ao prazo do corte' },
        releaseCutoffId: 'rc-web-1',
        updatedAt: '2026-08-20',
        tasks: [
          task('Fluxo de vinculação do autenticador', 'Helena Prado', 5, '2026-08-27', 'Em Andamento', '2026-08-20'),
        ],
      }),
      story({
        title: 'Serviço de emissão e validação de TOTP',
        status: 'A Fazer',
        technology: 'Backend',
        squad: 'Squad Core Bancário',
        size: 8,
        startDate: '2026-08-25',
        dueDate: '2026-09-15',
        completedDate: null,
        sprint: 'Sprint 35',
        externalDependency: { type: 'Nenhuma', status: 'não iniciado', expectedDate: null },
        thirdParty: noThirdParty,
        security: noSecurity,
        risk: { level: 'baixo', reason: 'Sem pendências' },
        releaseCutoffId: null,
        updatedAt: '2026-08-11',
        tasks: [
          task('Implementar geração de TOTP', 'Diego Santos', 5, '2026-09-10', 'A Fazer', '2026-08-11'),
        ],
      }),
    ],
  },
  {
    id: 'e10',
    key: 'EPIC-110',
    title: 'Chatbot de Suporte via HX',
    technologies: ['Frontend', 'Backend'],
    squads: ['Squad Onboarding', 'Squad Integrações'],
    milestoneDate: '2026-10-01',
    dueDate: '2026-10-22',
    stories: [
      story({
        title: 'Interface de chatbot com escalonamento humano',
        status: 'A Fazer',
        technology: 'Frontend',
        squad: 'Squad Onboarding',
        size: 8,
        startDate: '2026-09-01',
        dueDate: '2026-09-25',
        completedDate: null,
        sprint: 'Sprint 36',
        externalDependency: { type: 'HX', status: 'não iniciado', expectedDate: '2026-09-20' },
        thirdParty: noThirdParty,
        security: noSecurity,
        risk: { level: 'baixo', reason: 'Ainda não iniciado, sem pendências identificadas' },
        releaseCutoffId: null,
        updatedAt: '2026-08-05',
        tasks: [
          task('Prototipar fluxo de conversa', 'Ana Lima', 3, '2026-09-10', 'A Fazer', '2026-08-05'),
        ],
      }),
    ],
  },
]

export const ceremonies: Ceremony[] = [
  {
    id: 'c1',
    type: 'Subcomitê de Produtos',
    date: '2026-08-26',
    agendaItemKeys: ['EPIC-101', 'EPIC-104'],
    notes: 'Foco em dependências externas com HX e prazo de homologação PJ.',
  },
  {
    id: 'c2',
    type: 'Subcomitê de Produtos',
    date: '2026-09-09',
    agendaItemKeys: ['EPIC-102', 'EPIC-107', 'EPIC-109'],
    notes: 'Itens do corte de app de setembro (iOS/Android) e MFA Web Banking.',
  },
  {
    id: 'c3',
    type: 'Review',
    date: '2026-08-28',
    agendaItemKeys: ['HIST-308', 'HIST-312'],
    notes: 'Review de sprint das squads Onboarding e Web Banking.',
  },
  {
    id: 'c4',
    type: 'Planning',
    date: '2026-09-01',
    agendaItemKeys: ['EPIC-103', 'EPIC-105'],
    notes: 'Planning da Sprint 35.',
  },
  {
    id: 'c5',
    type: 'Refinamento',
    date: '2026-08-25',
    agendaItemKeys: ['EPIC-110'],
    notes: 'Refinamento do chatbot HX para detalhar critérios de aceite.',
  },
  {
    id: 'c6',
    type: 'Subcomitê de Produtos',
    date: '2026-09-23',
    agendaItemKeys: ['EPIC-105', 'EPIC-106'],
    notes: 'Status de homologação Salesforce e publicação no site institucional.',
  },
]

export const pareceres: Parecer[] = [
  {
    id: 'p1',
    itemKey: 'EPIC-106',
    itemTitle: 'Simulador de Crédito no Portal Institucional',
    date: '2026-08-12',
    resultado: 'aprovado com ressalvas',
    observacoes: 'Aprovado mediante inclusão de disclaimer de taxas no simulador.',
  },
  {
    id: 'p2',
    itemKey: 'EPIC-108',
    itemTitle: 'Widget de Saldo na Tela Inicial (Android)',
    date: '2026-08-01',
    resultado: 'aprovado',
    observacoes: 'Sem ressalvas.',
  },
  {
    id: 'p3',
    itemKey: 'EPIC-101',
    itemTitle: 'Abertura de Conta PJ Digital',
    date: '2026-08-05',
    resultado: 'aprovado com ressalvas',
    observacoes: 'Aprovado condicionado à conclusão do parecer de segurança do formulário PJ.',
  },
  {
    id: 'p4',
    itemKey: 'EPIC-104',
    itemTitle: 'Atendimento Digital via HX',
    date: '2026-08-19',
    resultado: 'pendente',
    observacoes: 'Aguardando desbloqueio do ambiente de homologação da HX para reavaliação.',
  },
]

export const releaseCutoffs: ReleaseCutoff[] = [
  { id: 'rc-ios-1', platform: 'iOS', version: '9.4.0', cutoffDate: '2026-09-04', releaseDate: '2026-09-11' },
  { id: 'rc-android-1', platform: 'Android', version: '9.4.0', cutoffDate: '2026-09-04', releaseDate: '2026-09-11' },
  { id: 'rc-web-1', platform: 'Web Banking', version: '2026.09-r1', cutoffDate: '2026-09-02', releaseDate: '2026-09-05' },
  { id: 'rc-ios-2', platform: 'iOS', version: '9.5.0', cutoffDate: '2026-09-25', releaseDate: '2026-10-02' },
  { id: 'rc-android-2', platform: 'Android', version: '9.5.0', cutoffDate: '2026-09-25', releaseDate: '2026-10-02' },
  { id: 'rc-web-2', platform: 'Web Banking', version: '2026.09-r2', cutoffDate: '2026-09-23', releaseDate: '2026-09-26' },
]

export const lastUpdated = '2026-08-21T09:12:00-03:00'
